/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tomatomb' at '16. 7. 16 오후 8:58' with Gradle 2.14
 *
 * @author tomatomb, @date 16. 7. 16 오후 8:58
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
